### ISSUE TITLE
Wrong twitter link in mobile

### ISSUE THREAD

**Issue by salgozino** [Fork-DAO/landing#1]
In https://github.com/Fork-DAO/landing/blob/910ccca47f87b7439622f383ba33e43a41439061/components/HeaderMobile.js#L29 the link points to a wrong twitter account 🫣

**Comment by herniadlf** [comment]
@salgozino thanks. Fixed in https://github.com/Fork-DAO/landing/commit/48b5c20c54460367aa27c7acf3875135209b2267 !
